# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Netdata add-on
version: "0.1.0"
slug: netdata
description: Netdata https://www.netdata.cloud/ Monitor everything in real time. For free
url: "https://github.com/Gamma-Software/netdata-homeassistant-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
stage: experimental
init: false
ports:
  19999/tcp: 19999
ports_description:
  19999/tcp: "netdata default port"
journald: true
privileged:
  - SYS_PTRACE
apparmor:
  - "unconfined"
options:
  hostname: homeassistant
  page_cache_size: 32
  dbengine_disk_space: 256
  enable_alarm: true
  enable_log: true
  #cloud_url: https://app.netdata.cloud
  #cloud_token: xxxxxxxxxxxxxxxxxxxxxxx
  #cloud_rooms:
  #  - ROOM
schema:
  hostname: str
  page_cache_size: int
  dbengine_disk_space: int
  enable_alarm: bool
  enable_log: bool
  #cloud_url: url
  #cloud_token: str
  #cloud_rooms:
  #  - str
image: "ghcr.io/Gamma-Software/{arch}-netdata-homeassistant-addon"
